repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
        files: ^cmds/|^iocsh/
      - id: trailing-whitespace
        files: ^cmds/|^iocsh/
